version: "3.9"
services:
  honeypot:
    build: .
    container_name: cyberbotalarm
    restart: unless-stopped
    ports:
      - "22:2222"      # SSH (auf Port 22 von außen)
      - "8080:8080"    # Web Honeypot
      - "9999:9999"    # Dashboard
      - "21:21"        # FTP
      - "23:23"        # Telnet
      - "3306:3306"    # MySQL
      - "6379:6379"    # Redis
      - "5432:5432"    # PostgreSQL Trap
      - "9200:9200"    # Elasticsearch Trap
    volumes:
      - ./data:/app/data
      - ./config.yml:/app/config.yml
    environment:
      - PYTHONUNBUFFERED=1
