"""Fake Linux Filesystem — täuschend echt"""
from core.honeytokens import get_fake_passwd, get_fake_shadow, get_fake_env_file

def build(tokens: dict) -> dict:
    env = get_fake_env_file(tokens)
    return {
        "/": ["bin", "etc", "home", "root", "tmp", "var", "usr", "proc", "sys"],
        "/etc": ["passwd", "shadow", "hosts", "hostname", "crontab", "nginx"],
        "/etc/passwd": get_fake_passwd(),
        "/etc/shadow": get_fake_shadow(),
        "/etc/hosts": "127.0.0.1 localhost\n127.0.1.1 ubuntu-server\n::1 localhost\n",
        "/etc/hostname": "ubuntu-server\n",
        "/etc/crontab": "*/5 * * * * root /usr/local/bin/backup.sh\n0 2 * * * root /usr/bin/certbot renew\n",
        "/etc/nginx": ["nginx.conf", "sites-enabled"],
        "/etc/nginx/nginx.conf": "worker_processes auto;\nevents { worker_connections 1024; }\nhttp { include /etc/nginx/sites-enabled/*; }\n",
        "/home": ["admin", "deploy"],
        "/home/admin": [".bash_history", ".ssh", ".env"],
        "/home/admin/.bash_history": "ls -la\ncd /var/www\ngit pull\nnpm run build\nsystemctl restart nginx\nmysql -u root -p\nhistory\n",
        "/home/admin/.ssh": ["authorized_keys"],
        "/home/admin/.ssh/authorized_keys": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQ... admin@workstation\n",
        "/home/admin/.env": env,
        "/home/deploy": [".bash_history"],
        "/home/deploy/.bash_history": "git clone https://github.com/company/app.git\ncd app\ndocker-compose up -d\n",
        "/root": [".bash_history", ".ssh", "backup", ".env"],
        "/root/.bash_history": "apt update && apt upgrade -y\nufw allow 22\nufw allow 80\nufw allow 443\niptables -L\nmysql -u root -pSecret123\ntail -f /var/log/auth.log\n",
        "/root/.ssh": ["authorized_keys", "id_rsa", "id_rsa.pub"],
        "/root/.ssh/id_rsa": "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAA... [honeytoken key]\n-----END OPENSSH PRIVATE KEY-----\n",
        "/root/.ssh/authorized_keys": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB... root@backup-server\n",
        "/root/.env": env,
        "/root/backup": ["db_backup_2024.sql.gz", "config_backup.tar.gz"],
        "/root/backup/db_backup_2024.sql.gz": "[binary data - 47MB]\n",
        "/tmp": [".tmp_installer", "sess_abc123"],
        "/var": ["log", "www"],
        "/var/log": ["auth.log", "syslog", "nginx"],
        "/var/log/auth.log": "May 15 02:31:12 ubuntu-server sshd[1234]: Accepted password for admin from 10.0.0.5 port 54321\nMay 15 03:12:44 ubuntu-server sshd[1235]: Accepted publickey for root from 10.0.0.1 port 22\n",
        "/var/log/syslog": "May 15 06:00:01 ubuntu-server CRON[2345]: (root) CMD (/usr/local/bin/backup.sh)\nMay 15 07:15:22 ubuntu-server kernel: [UFW BLOCK] IN=eth0 SRC=192.168.1.100\n",
        "/var/log/nginx": ["access.log", "error.log"],
        "/var/log/nginx/access.log": '192.168.1.1 - - [15/May/2024:06:00:01 +0000] "GET / HTTP/1.1" 200 612\n10.0.0.5 - - [15/May/2024:08:23:11 +0000] "POST /api/login HTTP/1.1" 200 48\n',
        "/var/www": ["html"],
        "/var/www/html": ["index.php", ".env", "wp-config.php"],
        "/var/www/html/.env": env,
        "/var/www/html/wp-config.php": f"<?php\ndefine('DB_NAME', 'wordpress');\ndefine('DB_USER', 'wpuser');\ndefine('DB_PASSWORD', '{tokens.get(\"db_password\",\"\")}');\ndefine('DB_HOST', 'localhost');\n",
        "/proc": ["cpuinfo", "meminfo", "version"],
        "/proc/cpuinfo": "processor : 0\nvendor_id : GenuineIntel\nmodel name : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz\ncpu cores : 4\n",
        "/proc/meminfo": "MemTotal:        8192000 kB\nMemFree:         2048000 kB\nMemAvailable:    4096000 kB\n",
        "/proc/version": "Linux version 5.15.0-1034-aws (buildd@ubuntu) (gcc-11)\n",
    }
